package com.example.form;

import com.example.entity.Employee;
import com.example.entity.Kitap;

import java.sql.*;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Esad
 */
public class Kutuphane extends javax.swing.JFrame {
    private EntityManagerFactory emf;
    private EntityManager em;

    /** Creates new form Kutuphane */
    public Kutuphane() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("example");
        em = emf.createEntityManager();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitapTable = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        kisiAdText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kisiMailText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        kisiTelText = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        kisiGuncelle = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        kitapOdunc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        kullaniciOdunc = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ayirtmaTarihi = new javax.swing.JTextField();
        oduncKaydet = new javax.swing.JButton();
        geriAlButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        kitapNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kitapAdiTextField = new javax.swing.JTextField();
        yazariTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yayinEviTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        durumComboBox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        kitapAra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        kitapGuncelle = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kitap No");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        jLabel18.setText("Durum");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Kullanıcı");

        kitapTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Kitap No", "Kitap Adı", "Yazarı", "Yayın Evi", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kitapTable);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton10.setText("sorgula");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField17)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("kitap listele", jPanel2);

        jLabel11.setText("Ad  :");

        kisiAdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisiAdTextActionPerformed(evt);
            }
        });

        jLabel12.setText("E-mail :");

        jLabel13.setText("Telefon :");

        jButton5.setText("Yeni Kişi Ekle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        kisiGuncelle.setText("Kişi Güncelle");
        kisiGuncelle.setEnabled(false);
        kisiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisiGuncelleActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(kisiGuncelle)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kisiTelText, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(kisiMailText, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(kisiAdText, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jButton4)
                            .addGap(113, 113, 113))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addContainerGap()))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kisiAdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(kisiMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(kisiTelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(kisiGuncelle)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("kişiler", jPanel4);

        jLabel14.setText("Kitap No :");

        jLabel15.setText("Kullanıcı No:");

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel16.setText("Ayırtma Tarihi :");

        oduncKaydet.setText("Kaydet");
        oduncKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oduncKaydetActionPerformed(evt);
            }
        });

        geriAlButton.setText("Kullanıcıdan Al");
        geriAlButton.setEnabled(false);
        geriAlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriAlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addComponent(jLabel16))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ayirtmaTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(oduncKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(kitapOdunc, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(kullaniciOdunc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geriAlButton)
                    .addComponent(jButton7))
                .addGap(152, 152, 152))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kitapOdunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(kullaniciOdunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayirtmaTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oduncKaydet)
                    .addComponent(geriAlButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ödünç alma", jPanel6);

        kitapNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Kitap No:");

        kitapAdiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapAdiTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Kitap Adı:");

        jLabel9.setText("Yazarı:");

        jLabel10.setText("Yayın Evi:");

        durumComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Var", "Yok" }));

        jLabel20.setText("Durum:");

        kitapAra.setText("...");
        kitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapAraActionPerformed(evt);
            }
        });

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kitapGuncelle.setText("Güncelle");
        kitapGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapGuncelleActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(durumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yayinEviTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(yazariTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(kitapAdiTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(kitapNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(kitapAra)
                        .addGap(212, 212, 212))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(kitapGuncelle)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitapAra)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(kitapAdiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(yazariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yayinEviTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(kitapGuncelle)
                    .addComponent(jButton1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("kitaplar", jPanel8);

        jMenu1.setText("File");

        jMenuItem1.setText("Open...");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("About");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* bu fonksiyon ile sistemde bulunan kitaplar silinir*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EntityTransaction tx = em.getTransaction();
        tx.begin();

        try {
            if(!kitapNo.getText().isEmpty()){
                Kitap kitap = em.find(Kitap.class, Integer.parseInt(kitapNo.getText()));
                em.remove(kitap);
                kitapNo.setText("");
                kitapAdiTextField.setText("");
                yazariTextField.setText("");
                yayinEviTextField.setText("");
            }
            tx.commit();
        } catch (Exception e) {
            tx.rollback();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    /* bu fonksiyon ile kitap id si girilen bir kitabın diğer bilgileri değiştirilebilir */
    private void kitapGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapGuncelleActionPerformed
        
         Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            if(!kitapNo.getText().isEmpty()){
                String adi = kitapAdiTextField.getText();
                String yazar = yazariTextField.getText();
                String yayinEvi = yayinEviTextField.getText();
                String durum = durumComboBox.getSelectedItem().toString();
                int c = sta.executeUpdate("UPDATE KITAPLAR SET"
                        + " kitap_ad='"+adi+"',yazar='"+yazar+"'"+ ",yayin_evi='"+yayinEvi+"',durum='"+durum+"'"
                        + " WHERE (kitap_id="+kitapNo.getText()+")");

            }
            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
}//GEN-LAST:event_kitapGuncelleActionPerformed
    /* bu fonksiyon ile sisteme yeni bir kitap eklenir */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        Connection con = null;
        try {
          Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          con = DriverManager.getConnection("jdbc:odbc:Database1");
          Statement sta = con.createStatement();

          //text alanlardan yeni kitap değerleri alınır
          String kitapAdi = kitapAdiTextField.getText();
          String yazar = yazariTextField.getText();
          String yayinEvi = yayinEviTextField.getText();
          String durum = durumComboBox.getSelectedItem().toString();
          int c = sta.executeUpdate("INSERT INTO KITAPLAR"
            + " (kitap_ad, yazar,yayin_evi,durum)"
            + " VALUES ('"+kitapAdi+"','"+yazar+"','"+yayinEvi+"','"+durum+"')");

          sta.close();
          con.close();
        } catch (Exception e) {
          System.err.println("Exception: "+e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed
    /* bu fonksiyon ile verilen kitap id si sistemde kayıtlı bir kitap olup olmadığı sorgulanır*/
    private void kitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapAraActionPerformed
      
        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String where = " ";
            if(!kitapNo.getText().isEmpty()){
                where = "WHERE "+"kitap_id ="+kitapNo.getText()+"";

                sta.execute("SELECT kitap_ad,yazar,yayin_evi,durum FROM KITAPLAR "+where);
                ResultSet rs = sta.getResultSet();

                while(rs.next()){
                    //bulunan bir sonuc var ise alanlar doldurulur
                    kitapAdiTextField.setText(rs.getString(1));
                    yazariTextField.setText(rs.getString(2));
                    yayinEviTextField.setText(rs.getString(3));
                    durumComboBox.setSelectedItem(rs.getString(4).toString());
                }
            }

            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
}//GEN-LAST:event_kitapAraActionPerformed

    private void kitapAdiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapAdiTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_kitapAdiTextFieldActionPerformed

    private void kitapNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapNoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_kitapNoActionPerformed
    /* bu fonksiyon ile sisteme kitap odunc alabilecek yeni bir kullanıcı eklenir*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String adi = kisiAdText.getText();
            String email = kisiMailText.getText();
            String telefon = kisiTelText.getText();
            int c = sta.executeUpdate("INSERT INTO KULLANICILAR"
                    + " (adi, email,telefon)"
                    + " VALUES ('"+adi+"','"+email+"','"+telefon+"')");

            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    /* bu fonksiyon ile sistemde bulunan kitaplar bir liste halinde ekranda gösterilir */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        try {
            String where = "";
            if(!jTextField2.getText().isEmpty())
                where = "where t.id = "+jTextField2.getText();
            List<Kitap> kitapList = em.createQuery("from Kitap t "+where).getResultList();

                DefaultTableModel tm = new DefaultTableModel(); 

                //kolon adları yazılıyor
                tm.addColumn("Kitap No");
                tm.addColumn("Kitap Adı");
                tm.addColumn("Yazarı");
                tm.addColumn("Yayın Evi");
                tm.addColumn("Durum");
                //satırlar dolduruluyor
                kitapList.forEach(kitap -> {
                    Object[] row = new Object[5];
                    row[0] = kitap.getId();
                    row[1] = kitap.getKitapAdi();
                    row[2] = kitap.getYazarAdi();
                    row[3] = kitap.getYayinevi();
                    row[4] = kitap.getDurum();
                    tm.addRow(row);
                });
                kitapTable.setModel(tm); //listeye ekleniyor
            tx.commit();
        } catch (Exception e) {
            tx.rollback();
        }

}//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void kisiAdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisiAdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kisiAdTextActionPerformed
    /* bu fonksiyon ile verilen kullanıcı adıyla kayıtlı sistemde bir kullanıcı olup olmadığı sorgulanır */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String where = " ";
            if(!kisiAdText.getText().isEmpty()){
                where = "WHERE "+"adi ='"+kisiAdText.getText()+"'";

                sta.execute("SELECT email,telefon FROM KULLANICILAR "+where);
                ResultSet rs = sta.getResultSet();
                //kullanıcı bulundu ise alanları doldur
                while(rs.next()){
                    kisiMailText.setText(rs.getString(1));
                    kisiTelText.setText(rs.getString(2));
                }
               kisiGuncelle.setEnabled(true); //kullanıcı var ise güncellemeyi aktiflestir
            }

            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    /* bu fonksiyon ile sistemdeki kullanıcıların diğer bilgileri güncellenebilir */
    private void kisiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisiGuncelleActionPerformed
        // TODO add your handling code here:
           Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String adi = kisiAdText.getText();
            String email = kisiMailText.getText();
            String telefon = kisiTelText.getText();
            int c = sta.executeUpdate("UPDATE KULLANICILAR SET"
                    + " email='"+email+"',telefon='"+telefon+"'"
                    + " WHERE (adi='"+adi+"')");

            kisiGuncelle.setEnabled(false);
            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_kisiGuncelleActionPerformed
    /* bu fonksiyon ile bir kullanıcıya odunc bir kitap atanır, veri tabanına kaydedilir */
    private void oduncKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oduncKaydetActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String kitap = kitapOdunc.getText();
            String kullanici = kullaniciOdunc.getText();
            String tarih = ayirtmaTarihi.getText();
            // kaydın odunc durumu 1 olacak şekilde tabloya eklenir
            int c = sta.executeUpdate("INSERT INTO KULLANICI_KITAP"
                    + " (kullanici_id, kitap_id,durum,ayirtma_tarihi)"
                    + " VALUES ('"+kullanici+"','"+kitap+"', '1','"+tarih+"')");
            // kitaplar tablosundan odunc alınan kitabın durumu 'yok' olarak degistirilir
            int d = sta.executeUpdate("UPDATE KITAPLAR SET"
                    + " durum='Yok'"
                    + " WHERE kitap_id="+kitap);

            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_oduncKaydetActionPerformed
    /* bu fonksiyon ile odunc alınmıs bir kitap geri iade edilir ve durum bilgisi guncellenir */
    private void geriAlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriAlButtonActionPerformed
        // TODO add your handling code here:

        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String kitap = kitapOdunc.getText();
            // kitap odunc durumu geri alınıyor
            int c = sta.executeUpdate("UPDATE KULLANICI_KITAP SET"
                    + " durum='0'"
                    + " WHERE kitap_id="+kitap);
            // odunc alınmıs kitap tekrar 'var' durumuna getiriliyor
            int d = sta.executeUpdate("UPDATE KITAPLAR SET"
                    + " durum='Var'"
                    + " WHERE kitap_id="+kitap);

            kitapOdunc.setText("");
            kullaniciOdunc.setText("");
            ayirtmaTarihi.setText("");

            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_geriAlButtonActionPerformed
    /* bu fonksiyon ile geri alma işlemi yapılmadan önce kitabın ödünç verilip verilmediği sorgulanır */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here
        Connection con = null;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Database1");
            Statement sta = con.createStatement();

            String where = " ";
            if(!kitapOdunc.getText().isEmpty()){
                where = "WHERE "+"kitap_id ="+kitapOdunc.getText()+" AND durum='1'";

                sta.execute("SELECT kullanici_id,ayirtma_tarihi FROM KULLANICI_KITAP "+where);
                ResultSet rs = sta.getResultSet();

                while(rs.next()){
                    // kitap odunc verilmis ise alanlar doldurulur
                    kullaniciOdunc.setText(rs.getString(1));
                    ayirtmaTarihi.setText(rs.getString(2));
                    //odunc durumdan geri alma secenegi aktiflestirilir
                    geriAlButton.setEnabled(true);
                }
            }
            sta.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ayirtmaTarihi;
    private javax.swing.JComboBox durumComboBox;
    private javax.swing.JButton geriAlButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField kisiAdText;
    private javax.swing.JButton kisiGuncelle;
    private javax.swing.JTextField kisiMailText;
    private javax.swing.JTextField kisiTelText;
    private javax.swing.JTextField kitapAdiTextField;
    private javax.swing.JButton kitapAra;
    private javax.swing.JButton kitapGuncelle;
    private javax.swing.JTextField kitapNo;
    private javax.swing.JTextField kitapOdunc;
    private javax.swing.JTable kitapTable;
    private javax.swing.JTextField kullaniciOdunc;
    private javax.swing.JButton oduncKaydet;
    private javax.swing.JTextField yayinEviTextField;
    private javax.swing.JTextField yazariTextField;
    // End of variables declaration//GEN-END:variables

}
